// import { Inter } from 'next/font/google';
import { Rubik } from 'next/font/google';
import './globals.css';

// const inter = Inter({ subsets: ['latin'] });
const rubik = Rubik({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className='dark'>
      <body className={rubik.className + ' bg-background'}>{children}</body>
    </html>
  );
}
