### User Registration
POST https://shawrty-api.vercel.app/api/users/register
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "securepassword"
}

### User Login
POST http://localhost:8000/api/users/login
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "securepassword"
}

### Create Shortened URL (Replace <token> with the JWT obtained from login)
POST http://localhost:8000/api/urls/shorten
Content-Type: application/json
Cookie: token=<your_token_here>

{
  "originalUrl": "https://google.com"
}

### Get Urls of the original user
GET http://localhost:8000/api/urls/
Cookie: token=<your_token_here>


### Get Original URL (Replace <shortenedUrl> with the actual shortened URL obtained from creation)
GET http://localhost:8000/api/urls/1WUQW9
